// template/template/angular/crud/app/entities/${comp}/${comp}-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { I${ucomp} } from 'app/shared/model/${comp}.model';

@Component({
  selector: 'jhi-${lcomp}-detail',
  templateUrl: './${comp}-detail.component.html',
})
export class ${ucomp}DetailComponent implements OnInit {
  ${comp}: I${ucomp} | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ ${comp} }) => (this.${comp} = ${comp}));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="${comp}">
            <h2><span>Address</span> {{ ${comp}.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Address 1</span></dt>
                <dd>
                    <span>{{ ${comp}.address1 }}</span>
                </dd>
                <dt><span>Address 2</span></dt>
                <dd>
                    <span>{{ ${comp}.address2 }}</span>
                </dd>
                <dt><span>City</span></dt>
                <dd>
                    <span>{{ ${comp}.city }}</span>
                </dd>
                <dt><span>Postcode</span></dt>
                <dd>
                    <span>{{ ${comp}.postcode }}</span>
                </dd>
                <dt><span>Country</span></dt>
                <dd>
                    <span>{{ ${comp}.country }}</span>
                </dd>
                <dt><span>Customer</span></dt>
                <dd>
                    <div *ngIf="${comp}.customer">
                        <a [routerLink]="['/customer', ${comp}.customer?.id, 'view']">{{ ${comp}.customer?.id }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/${comp}', ${comp}.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// template/template/react/crud/app/entities/${comp}/${comp}-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './${comp}.reducer';
import { I${ucomp} } from 'app/shared/model/${comp}.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface I${ucomp}DetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ${ucomp}Detail = (props: I${ucomp}DetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { ${comp}Entity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          Address [<b>{${comp}Entity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="address1">Address 1</span>
          </dt>
          <dd>{${comp}Entity.address1}</dd>
          <dt>
            <span id="address2">Address 2</span>
          </dt>
          <dd>{${comp}Entity.address2}</dd>
          <dt>
            <span id="city">City</span>
          </dt>
          <dd>{${comp}Entity.city}</dd>
          <dt>
            <span id="postcode">Postcode</span>
          </dt>
          <dd>{${comp}Entity.postcode}</dd>
          <dt>
            <span id="country">Country</span>
          </dt>
          <dd>{${comp}Entity.country}</dd>
          <dt>Customer</dt>
          <dd>{${comp}Entity.customer ? ${comp}Entity.customer.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/${comp}" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/${comp}/@@{${comp}Entity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ ${comp} }: IRootState) => ({
  ${comp}Entity: ${comp}.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(${ucomp}Detail);
