// template/template/react/crud/app/entities/${comp}/${comp}.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './${comp}.reducer';
import { I${ucomp} } from 'app/shared/model/${comp}.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface I${ucomp}Props extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const ${ucomp} = (props: I${ucomp}Props) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `@@{paginationState.sort},@@{paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=@@{paginationState.activePage}&sort=@@{paginationState.sort},@@{paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`@@{props.location.pathname}@@{endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const { ${comp}List, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="${comp}-heading">
        Addresses
        <Link to={`@@{match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Address
        </Link>
      </h2>
      <div className="table-responsive">
        {${comp}List && ${comp}List.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  ID <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('address1')}>
                  Address 1 <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('address2')}>
                  Address 2 <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('city')}>
                  City <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('postcode')}>
                  Postcode <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('country')}>
                  Country <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  Customer <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {${comp}List.map((${comp}, i) => (
                <tr key={`entity-@@{i}`}>
                  <td>
                    <Button tag={Link} to={`@@{match.url}/@@{${comp}.id}`} color="link" size="sm">
                      {${comp}.id}
                    </Button>
                  </td>
                  <td>{${comp}.address1}</td>
                  <td>{${comp}.address2}</td>
                  <td>{${comp}.city}</td>
                  <td>{${comp}.postcode}</td>
                  <td>{${comp}.country}</td>
                  <td>{${comp}.customer ? <Link to={`customer/@@{${comp}.customer.id}`}>{${comp}.customer.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`@@{match.url}/@@{${comp}.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`@@{match.url}/@@{${comp}.id}/edit?page=@@{paginationState.activePage}&sort=@@{paginationState.sort},@@{paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`@@{match.url}/@@{${comp}.id}/delete?page=@@{paginationState.activePage}&sort=@@{paginationState.sort},@@{paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Addresses found</div>
        )}
      </div>
      {props.totalItems ? (
        <div className={${comp}List && ${comp}List.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ ${comp} }: IRootState) => ({
  ${comp}List: ${comp}.entities,
  loading: ${comp}.loading,
  totalItems: ${comp}.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(${ucomp});

// template/template/angular/crud/app/entities/${comp}/${comp}.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { I${ucomp} } from 'app/shared/model/${comp}.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { ${ucomp}Service } from './${comp}.service';
import { ${ucomp}DeleteDialogComponent } from './${comp}-delete-dialog.component';

@Component({
  selector: 'jhi-${lcomp}',
  templateUrl: './${comp}.component.html',
})
export class ${ucomp}Component implements OnInit, OnDestroy {
  ${comp}es?: I${ucomp}[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected ${comp}Service: ${ucomp}Service,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.${comp}Service
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<I${ucomp}[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeIn${ucomp}es();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: I${ucomp}): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeIn${ucomp}es(): void {
    this.eventSubscriber = this.eventManager.subscribe('${comp}ListModification', () => this.loadPage());
  }

  delete(${comp}: I${ucomp}): void {
    const modalRef = this.modalService.open(${ucomp}DeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.${comp} = ${comp};
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: I${ucomp}[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/${comp}'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.${comp}es = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span>Addresses</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-${comp}" [routerLink]="['/${comp}/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Address
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="${comp}es?.length === 0">
        <span>No ${comp}es found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="${comp}es && ${comp}es.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span>ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="address1"><span>Address 1</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="address2"><span>Address 2</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="city"><span>City</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="postcode"><span>Postcode</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="country"><span>Country</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="customer.id"><span>Customer</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let ${comp} of ${comp}es ;trackBy: trackId">
                    <td><a [routerLink]="['/${comp}', ${comp}.id, 'view']">{{ ${comp}.id }}</a></td>
                    <td>{{ ${comp}.address1 }}</td>
                    <td>{{ ${comp}.address2 }}</td>
                    <td>{{ ${comp}.city }}</td>
                    <td>{{ ${comp}.postcode }}</td>
                    <td>{{ ${comp}.country }}</td>
                    <td>
                        <div *ngIf="${comp}.customer">
                            <a [routerLink]="['/customer', ${comp}.customer?.id, 'view']" >{{ ${comp}.customer?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/${comp}', ${comp}.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/${comp}', ${comp}.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(${comp})"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="${comp}es && ${comp}es.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
